### PR TITLE
Enable FFI on PHP 7.4

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by nikic** [comment]
Should also be enabled on `-master`?

**Comment by cdosoftei** [comment]
:+1: It would be great to include FFI in the PHP build! Currently running tests inside Docker containers so prerequisites are in place, but it incurs more overhead.

**Comment by vkhramtsov** [comment]
Any news here? I looking forward for FFI extension in travis builds

**Comment by mustafa-travisci** [comment]
#62 closes this one.

**Pull request closed without merging**
