### PR TITLE
Link against oniguruma statically

### PR DESCRIPTION
**Pull request by nikic**

### CODE REVIEW

**Comment by ostrolucky** [comment]
@BanzaiMan seeing you helped merge https://github.com/travis-ci/php-src-builder/pull/31, can you take a look here as well, please? People are avoiding testing PHP 7.4 snapshots because of this

**Comment by nikic** [comment]
Ping

**Comment by sebastianbergmann** [comment]
Thank you, @BanzaiMan. How often is PHP `master` updated on Travis? I don't think it's actually "nightly".

**Comment by nikic** [comment]
@sebastianbergmann The build does happen every day, see https://travis-ci.org/travis-ci/php-src-builder/builds -- it just doesn't always succeed. If there are upstream changes in the build system (of which there are a lot in 7.4) then Travis may fail to produce new snapshot builds for a while, until the issue is resolved.

This change should've gone out already though. Are you still seeing issues?

**Comment by sebastianbergmann** [comment]
Sorry for the noise, seems to work now.

**Comment by sebastianbergmann** [comment]
Sorry for the noise, seems to work now. I assumed this issue to still exist as I am still seeing [build failures](https://travis-ci.org/sebastianbergmann/phpunit/jobs/525584585) of PHPUnit on PHP 8.0-dev that should be fixed by https://github.com/php/php-src/commit/e311f2a320b07b6d210c5b1db24a37a0259859f1.

**Comment by nikic** [comment]
@sebastianbergmann That's odd. Your build log says "PHP 8.0.0-dev (cli) (built: Feb 11 2019 07:59:12) ( ZTS )", so this build is indeed outdated. However I got a recent build in apcu: https://travis-ci.org/krakjoe/apcu/jobs/525534805#L492 Both run on trusty builders, so I'm not sure where this difference comes from.

**Comment by nikic** [comment]
@sebastianbergmann Oh, I see, you are using `master` instead of `nightly`. Probably the aliasing broke at some point...

**Comment by sebastianbergmann** [comment]
*sigh* Should I change `master` to `nightly` in all my projects now or wait until the aliasing issue is fixed?

**Comment by nikic** [comment]
I've verified that nightly vs master is indeed what makes the difference here. Looking at the build logs, both artifacts are uploaded to AWS:

```
INFO: uploading: /home/travis/build/travis-ci/php-src-builder/14.04/php-master.tar.bz2 (size: 62MB)
  download_url: https://s3.amazonaws.com/[secure]/binaries/ubuntu/14.04/x86_64/php-master.tar.bz2
INFO: uploading: /home/travis/build/travis-ci/php-src-builder/14.04/php-master.tar.bz2.sha256sum.txt (size: 85B)
  download_url: https://s3.amazonaws.com/[secure]/binaries/ubuntu/14.04/x86_64/php-master.tar.bz2.sha256sum.txt
INFO: uploading: /home/travis/build/travis-ci/php-src-builder/14.04/php-nightly.tar.bz2 (size: 62MB)
  download_url: https://s3.amazonaws.com/[secure]/binaries/ubuntu/14.04/x86_64/php-nightly.tar.bz2
INFO: uploading: /home/travis/build/travis-ci/php-src-builder/14.04/php-nightly.tar.bz2.sha256sum.txt (size: 86B)
  download_url: https://s3.amazonaws.com/[secure]/binaries/ubuntu/14.04/x86_64/php-nightly.tar.bz2.sha256sum.txt
```

The actual downloads happen from Google Cloud Storage though:

```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/14.04/x86_64/php-master.tar.bz2
```

I have no idea how the artifacts get from AWS to GCS though -- probably some handling for the php-master archive is missing.

**Comment by BanzaiMan** [comment]
There is a lag between the S3 upload to php-arc-builder, and the sync from S3 to GCS, where your builds will pull the archives. (To save on bandwidth cost.)

I’m not sure how the names `master` and `nightly` should work differently at the moment.

**Pull request merged**
