### PR TITLE
Install oniguruma

### PR DESCRIPTION
**Pull request by nikic**
PHP 7.4 and upwards no longer bundle oniguruma, so it has to be provided by the system. This PR installs libonig-dev and also adds a custom pkgconfig file, because the oniguruma that ships with trusty doesn't have it's own pc file yet.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Seems broken. https://travis-ci.org/travis-ci/php-src-builder/jobs/499227645#L2639

**Comment by nikic** [comment]
@BanzaiMan This is due to #32, apparently the go-pear.phar on pear.php.net is not the latest one and does not have the PHP 8 compatibility fixes :/

**Comment by BanzaiMan** [comment]
That's unfortunate. Let's revert #32, then.

**Comment by nikic** [comment]
The issue with pear.php.net should be fixed now, let's see if it works now...

**Comment by nikic** [comment]
Build is green :)

**Comment by nikic** [comment]
ping

**Comment by nikic** [comment]
This is causing the following error when running jobs against nightly:

> php: error while loading shared libraries: libonig.so.2: cannot open shared object file: No such file or directory

I guess something more needs to be done to make sure that the libonig.so we're linking against is also available on the image?

**Comment by BanzaiMan** [comment]
Looks like we would have to install `libonig-dev` for the PHP nightly builds.

**Comment by BanzaiMan** [comment]
I wonder if PHP can be statically compiled. 🤔

**Comment by nikic** [comment]
It should be possible to link oniguruma statically, but we'd also have to build it ourselves for that. We can only link dynamically against the system library.

**Comment by nikic** [comment]
Another possibility would be to ship the .so with the binary and either move it to the right location, or specify an rpath during linking.

**Pull request merged**
