### PR TITLE
Use --with-zip instead of --enable-zip

### PR DESCRIPTION
**Pull request by nikic**
Option renamed in 7.4.

### CODE REVIEW

**Comment by sminnee** [comment]
FYI check for conflicts with #40

**Comment by BanzaiMan** [comment]
@sminnee Could you combine this with #40?

**Comment by sminnee** [comment]
Sure I can cherry pick this commit into 40 and then you can close this off.

**Comment by sminnee** [comment]
This commit has been cherry-picked into #40 here https://github.com/travis-ci/php-src-builder/pull/40/commits/8dbd57d2bdc92efeab0e9f5d0068bc42b475a819

**Pull request closed without merging**
