### PR TITLE
Make configure compatible with PHP 7.4

### PR DESCRIPTION
**Pull request by nikic**
This contains two changes:

 * First commit: Combine all configure files into one script. Otherwise we'd need many files to account for the small differences between each PHP version.
 * Second commit: Adjust configure for changes in PHP 7.4. Out of the used options, only GD is affected.

### CODE REVIEW

**Comment by nikic** [comment]
Always getting this now:

> ERROR: This build could not be run. Reason: bad_request

Some kind of infra issue?

**Comment by nikic** [comment]
Everything apart from precise is working, and I'm not going to spend more time on precise... it now fails later in the build (building intl rather that configuring intl).

**Comment by nikic** [comment]
These changes are probably not sufficient anymore and the build is now likely to fail due to a missing libonig dependency.

@BanzaiMan To get an additional dependency, would it be sufficient to install `libonig-dev` in `.travis.yml`, or would this result in a missing shared object dependency when the built binary is used? That is, does something additional need to be done to make sure that the necessary SO is also present in the container/VM in some manner?

**Comment by BanzaiMan** [comment]
Not sure if I like the "config" generation idea. The configurations will remain mostly static, once you take the Ubuntu release and the PHP version into consideration. Using a "generator" (which is driven by a few `if; then echo; fi` logic reduces readability of the archive's configuration.

**Comment by nikic** [comment]
The problem with separate configure files is that there is something of a combinatorial explosion, and it is easy for things to get out of sync. For example, right now there is a xenial-7.2 file, but the same changes that were made there obviously also apply to xenial-7.3, xenial-7.4 and xenial-master. They also apply to trusty-7.2, trusty-7.3, trusty-7.4 and trusty-master for that matter. Yet none of these files are present.

This was okay until now because the differences were cosmetic (they avoid configure warnings), but now that there actually are important differences in configure options, it is necessary to have all these files. We'd need at least xenial-7.4, xenial-master, trusty-7.4, trusty-master to get things working again, and all four of those would actually be identical. All four would need to be changed when configure options change in PHP (and there are still a few more changes incoming for 7.4).

Having everything in one file with a few conditionals makes sure that configuration stays in sync, and also makes it obvious what the differences between versions/distros are without having to resort to diff.

**Comment by nikic** [comment]
Ping

**Comment by nikic** [comment]
Another ping

**Comment by nikic** [comment]
Ping :)

**Comment by sminnee** [comment]
Right now it looks like the PHP 7.4 builds don't include GD. It would be nice to get this over the line to remedy that!

**Comment by BanzaiMan** [comment]
Thanks for the pings, but I still believe that having separate config files is better here.

**Comment by nikic** [comment]
Fair enough, I'll leave this to you then.

**Comment by ausi** [comment]
I created a followup pull request that uses separate config files in #34

**Pull request closed without merging**
